[package]
name = "rocket-api-rest"
version = "0.1.0"
authors = ["Diego Vázquez <alu0101014326@ull.edu.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]